# Default values for consul-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/consul-exporter
  tag: v0.3.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 9107
  annotations: {}

resourcecs: {}

consul:
  ## Address (host and port) of the consul node(s) (comma seperated list) we should connect to.
  ##
  server: localhost:8500

  ## Address

  ## If true, query stats for all nodes in the cluster, rather than just the
  ## node we connect to.
  ##
  all: true

  ## If true, query stats for all indices in the cluster.
  ##
  indices: true


  ssl:
    ## If true, a secure connection to Consul cluster is used (requires SSL certs below)
    ##
    enabled: false

    ca:

      ## PEM that contains trusted CAs used for setting up secure Consul connection
      ##
      # pem:

    client:

      ## PEM that contains the client cert to connect to Consul.
      ##
      # pem:

      ## Private key for client auth when connecting to Consul
      ##
      # key:

web:
  ## Path under which to expose metrics.
  ##
  path: /metrics

